import { defineType, defineField } from 'sanity'
import { Text } from 'lucide-react'

export default defineType({
    name: 'uiStrings',
    title: 'UI Strings',
    type: 'document',
    icon: Text,
    groups: [
        { name: 'notFound', title: '404 Page' },
        { name: 'system', title: 'System' },
        { name: 'navigation', title: 'Navigation' },
        { name: 'accessibility', title: 'Accessibility' },
        { name: 'forms', title: 'Forms & Validation' },
        { name: 'memberships', title: 'Memberships' },
        { name: 'routes', title: 'Route Paths' },

        { name: 'general', title: 'General' },
    ],
    fields: [
        defineField({
            name: 'language',
            title: 'Language',
            type: 'string',
            description: 'Select the language for this document',
            options: {
                list: [
                    { title: 'English', value: 'en' },
                    { title: 'Italiano', value: 'it' },
                ],
            },
            validation: (Rule) => Rule.required(),
        }),
        // 404 Page Fields
        defineField({
            name: 'notFoundBadge',
            title: '404 Badge Text',
            type: 'string',
            group: 'notFound',
            initialValue: 'Error 404',
        }),
        defineField({
            name: 'notFoundTitle',
            title: '404 Title',
            type: 'string',
            group: 'notFound',
            initialValue: 'Lost in Data.',
            description: 'Use {highlight} to wrap the highlighted word, e.g., "Lost in {highlight}Data.{/highlight}"',
        }),
        defineField({
            name: 'notFoundDescription',
            title: '404 Description',
            type: 'text',
            group: 'notFound',
            rows: 2,
            initialValue: 'The page you are looking for has been moved, removed, or never existed in our strategy framework.',
        }),
        defineField({
            name: 'notFoundHomeButtonText',
            title: 'Home Button Text',
            type: 'string',
            group: 'notFound',
            initialValue: 'Return Home',
        }),
        defineField({
            name: 'notFoundContactButtonText',
            title: 'Contact Button Text',
            type: 'string',
            group: 'notFound',
            initialValue: 'Contact Support',
        }),
        defineField({
            name: 'notFoundQuickLinksTitle',
            title: 'Quick Links Section Title',
            type: 'string',
            group: 'notFound',
            initialValue: 'Popular Insights',
        }),
        defineField({
            name: 'notFoundQuickLinks',
            title: 'Quick Links',
            type: 'array',
            group: 'notFound',
            of: [{
                type: 'object',
                fields: [
                    defineField({ name: 'label', title: 'Label', type: 'string' }),
                    defineField({ name: 'href', title: 'Link', type: 'string' }),
                ],
                preview: {
                    select: { title: 'label', subtitle: 'href' },
                },
            }],
        }),

        // System Strings
        defineField({
            name: 'systemLoading',
            title: 'Loading text',
            type: 'string',
            group: 'system',
            initialValue: 'Loading...',
        }),
        defineField({
            name: 'systemError',
            title: 'Error Badge / Title',
            type: 'string',
            group: 'system',
            initialValue: 'Error',
        }),
        defineField({
            name: 'systemRetry',
            title: 'Retry Button',
            type: 'string',
            group: 'system',
            initialValue: 'Retry',
        }),
        defineField({
            name: 'comingSoonTitle',
            title: 'Coming Soon Title',
            type: 'string',
            group: 'system',
            initialValue: 'Coming Soon',
        }),
        defineField({
            name: 'comingSoonMessage',
            title: 'Coming Soon Message',
            type: 'text',
            group: 'system',
            initialValue: 'This page is currently being updated.',
        }),

        // Navigation Strings
        defineField({
            name: 'mobileMenuOpenLabel',
            title: 'Mobile Menu Open Label (Accessibility)',
            type: 'string',
            group: 'navigation',
            initialValue: 'Open menu',
        }),
        defineField({
            name: 'mobileMenuCloseLabel',
            title: 'Mobile Menu Close Label (Accessibility)',
            type: 'string',
            group: 'navigation',
            initialValue: 'Close menu',
        }),
        defineField({
            name: 'navigationBackLabel',
            title: 'Back Label',
            type: 'string',
            group: 'navigation',
            initialValue: 'Back',
        }),
        defineField({
            name: 'exploreServicesLabel',
            title: 'Explore Services Label',
            type: 'string',
            group: 'navigation',
            initialValue: 'Explore Services',
        }),
        defineField({
            name: 'logoAriaLabel',
            title: 'Logo Aria Label (Home Link)',
            type: 'string',
            group: 'navigation',
            initialValue: 'Go to Homepage',
            validation: Rule => Rule.required(),
        }),
        defineField({
            name: 'skipToContentLabel',
            title: 'Skip to Content Label',
            type: 'string',
            group: 'accessibility',
            initialValue: 'Skip to content',
        }),

        // Memberships Strings
        defineField({
            name: 'membershipSuccessTitle',
            title: 'Success Page Title',
            type: 'string',
            group: 'memberships',
            initialValue: 'Welcome to the Community!',
        }),
        defineField({
            name: 'membershipSuccessMessage',
            title: 'Success Page Message',
            type: 'text',
            group: 'memberships',
            rows: 3,
            initialValue: "Your membership has been activated successfully. You'll receive an email with your exclusive Discord invite link within 24 hours.",
        }),
        defineField({
            name: 'membershipProcessingText',
            title: 'Processing Payment Text',
            type: 'string',
            group: 'memberships',
            initialValue: 'Processing your payment...',
        }),
        defineField({
            name: 'membershipOrderReferencePrefix',
            title: 'Order Reference Prefix',
            type: 'string',
            group: 'memberships',
            initialValue: 'Order reference:',
        }),
        defineField({
            name: 'membershipReturnHomeButton',
            title: 'Return Home Button',
            type: 'string',
            group: 'memberships',
            initialValue: 'Return Home',
        }),
        defineField({
            name: 'membershipContactSupportButton',
            title: 'Contact Support Button',
            type: 'string',
            group: 'memberships',
            initialValue: 'Contact Support',
        }),

        // Forms & Validation Strings
        defineField({
            name: 'formSubmitButton',
            title: 'Submit Button Default',
            type: 'string',
            group: 'forms',
            initialValue: 'Submit Request',
            validation: Rule => Rule.required(),
        }),
        defineField({
            name: 'formSubmittingText',
            title: 'Submitting Text',
            type: 'string',
            group: 'forms',
            initialValue: 'Submitting...',
            validation: Rule => Rule.required(),
        }),
        defineField({
            name: 'formSuccessTitle',
            title: 'Success Message Title',
            type: 'string',
            group: 'forms',
            initialValue: 'Request submitted successfully!',
            validation: Rule => Rule.required(),
        }),
        defineField({
            name: 'formErrorTitle',
            title: 'Error Message Title',
            type: 'string',
            group: 'forms',
            initialValue: 'Failed to submit request',
            validation: Rule => Rule.required(),
        }),
        defineField({
            name: 'formRequiredFieldLabel',
            title: 'Required Field Indicator (screen readers)',
            type: 'string',
            group: 'forms',
            initialValue: '(required)',
        }),
        defineField({
            name: 'formRequiredError',
            title: 'Required Field Error Message',
            type: 'string',
            group: 'forms',
            initialValue: 'This field is required.',
            validation: Rule => Rule.required(),
        }),
        defineField({
            name: 'formEmailError',
            title: 'Invalid Email Error Message',
            type: 'string',
            group: 'forms',
            initialValue: 'Please enter a valid email address.',
            validation: Rule => Rule.required(),
        }),

        // General UI Strings
        defineField({
            name: 'draftModeLabel',
            title: 'Draft Mode Label',
            type: 'string',
            group: 'general',
            initialValue: 'Draft Mode',
        }),
        defineField({
            name: 'draftModeExitText',
            title: 'Draft Mode Exit Text',
            type: 'string',
            group: 'general',
            initialValue: 'Exit',
        }),
        defineField({
            name: 'readyToStartBadge',
            title: 'Ready to Start Badge',
            type: 'string',
            group: 'general',
            initialValue: 'Ready to Start?',
        }),

        // System Strings - Errors
        defineField({
            name: 'sectionErrorTitle',
            title: 'Section Error Title',
            type: 'string',
            group: 'system',
            initialValue: 'Section Error',
        }),
        defineField({
            name: 'sectionErrorMessage',
            title: 'Section Error Message Default',
            type: 'string',
            group: 'system',
            initialValue: 'Unknown error',
        }),

        // Accessibility & Controls
        defineField({
            name: 'paginationPrev',
            title: 'Pagination Previous Label',
            type: 'string',
            group: 'navigation',
            initialValue: 'Previous',
        }),
        defineField({
            name: 'paginationNext',
            title: 'Pagination Next Label',
            type: 'string',
            group: 'navigation',
            initialValue: 'Next',
        }),
        defineField({
            name: 'carouselPrev',
            title: 'Carousel Previous Label',
            type: 'string',
            group: 'navigation',
            initialValue: 'Previous slide',
        }),
        defineField({
            name: 'carouselNext',
            title: 'Carousel Next Label',
            type: 'string',
            group: 'navigation',
            initialValue: 'Next slide',
        }),

        // Links & Actions
        defineField({
            name: 'exploreLabel',
            title: 'Explore Link Label',
            type: 'string',
            group: 'navigation',
            initialValue: 'Explore',
        }),
        defineField({
            name: 'freeTrialSuffix',
            title: 'Free Trial Suffix',
            type: 'string',
            group: 'general',
            initialValue: 'free trial',
            description: 'Text displayed after trial period, e.g. "7 days free trial"',
        }),

        // Memberships Page Labels
        defineField({
            name: 'insideChannelsLabel',
            title: 'Inside Channels Label',
            type: 'string',
            group: 'memberships',
            initialValue: 'Inside the private channels you will find:',
        }),

        // Checkout States
        defineField({
            name: 'checkoutProcessingText',
            title: 'Checkout Processing Text',
            type: 'string',
            group: 'memberships',
            initialValue: 'Processing...',
        }),
        defineField({
            name: 'checkoutErrorText',
            title: 'Checkout Error Text',
            type: 'string',
            group: 'memberships',
            initialValue: 'Something went wrong. Please try again.',
        }),

        // Generic Form Labels (reusable across pages)
        defineField({
            name: 'formNameLabel',
            title: 'Name Field Label',
            type: 'string',
            group: 'forms',
            initialValue: 'Full Name',
        }),
        defineField({
            name: 'formNamePlaceholder',
            title: 'Name Field Placeholder',
            type: 'string',
            group: 'forms',
            initialValue: 'Your full name',
        }),
        defineField({
            name: 'formEmailLabel',
            title: 'Email Field Label',
            type: 'string',
            group: 'forms',
            initialValue: 'Email Address',
        }),
        defineField({
            name: 'formEmailPlaceholder',
            title: 'Email Field Placeholder',
            type: 'string',
            group: 'forms',
            initialValue: 'your@email.com',
        }),
        defineField({
            name: 'formCountryLabel',
            title: 'Country Field Label',
            type: 'string',
            group: 'forms',
            initialValue: 'Country of Residence',
        }),
        defineField({
            name: 'formCountryPlaceholder',
            title: 'Country Field Placeholder',
            type: 'string',
            group: 'forms',
            initialValue: 'e.g., Switzerland, United States, etc.',
        }),
        defineField({
            name: 'formInterestLabel',
            title: 'Interest Field Label',
            type: 'string',
            group: 'forms',
            initialValue: 'Area of Interest',
        }),
        defineField({
            name: 'formInterestPlaceholder',
            title: 'Interest Field Placeholder',
            type: 'string',
            group: 'forms',
            initialValue: 'Select an area of interest',
        }),
        defineField({
            name: 'formMessageLabel',
            title: 'Message Field Label',
            type: 'string',
            group: 'forms',
            initialValue: 'Message',
        }),
        defineField({
            name: 'formMessagePlaceholder',
            title: 'Message Field Placeholder',
            type: 'string',
            group: 'forms',
            initialValue: 'Briefly describe your situation, objectives, or question.',
        }),

        // Accessibility Labels (SR-Only, ARIA)
        defineField({
            name: 'spinnerLoadingLabel',
            title: 'Spinner Loading Label',
            type: 'string',
            group: 'accessibility',
            initialValue: 'Loading',
            description: 'Aria-label for loading spinners',
        }),
        defineField({
            name: 'paginationEllipsis',
            title: 'Pagination Ellipsis Label',
            type: 'string',
            group: 'accessibility',
            initialValue: 'More pages',
            description: 'Screen reader text for pagination ellipsis',
        }),
        defineField({
            name: 'sidebarToggleLabel',
            title: 'Sidebar Toggle Label',
            type: 'string',
            group: 'accessibility',
            initialValue: 'Toggle Sidebar',
            description: 'Aria-label and sr-only text for sidebar toggle button',
        }),
        defineField({
            name: 'sheetCloseLabel',
            title: 'Sheet Close Label',
            type: 'string',
            group: 'accessibility',
            initialValue: 'Close',
            description: 'Screen reader text for sheet close button',
        }),
        defineField({
            name: 'dialogCloseLabel',
            title: 'Dialog Close Label',
            type: 'string',
            group: 'accessibility',
            initialValue: 'Close',
            description: 'Screen reader text for dialog close button',
        }),
        defineField({
            name: 'breadcrumbAriaLabel',
            title: 'Breadcrumb Aria Label',
            type: 'string',
            group: 'accessibility',
            initialValue: 'breadcrumb',
            description: 'Aria-label for breadcrumb navigation',
        }),
        defineField({
            name: 'breadcrumbMoreLabel',
            title: 'Breadcrumb More Label',
            type: 'string',
            group: 'accessibility',
            initialValue: 'More',
            description: 'Screen reader text for breadcrumb ellipsis',
        }),
        defineField({
            name: 'adminLoadingText',
            title: 'Admin Loading Text',
            type: 'string',
            group: 'system',
            initialValue: 'Loading Sanity Studio...',
            description: 'Text shown while Sanity Studio is loading',
        }),
        // Route Paths (Centralized Management)
        defineField({
            name: 'contactRoute',
            title: 'Contact Page Route',
            type: 'string',
            group: 'routes',
            initialValue: '/contact',
            validation: Rule => Rule.required(),
        }),
        defineField({
            name: 'membershipsRoute',
            title: 'Memberships Page Route',
            type: 'string',
            group: 'routes',
            initialValue: '/memberships',
            validation: Rule => Rule.required(),
        }),
        defineField({
            name: 'solutionsRoute',
            title: 'Solutions Page Route',
            type: 'string',
            group: 'routes',
            initialValue: '/solutions',
            validation: Rule => Rule.required(),
        }),
        defineField({
            name: 'loginRoute',
            title: 'Login Page Route',
            type: 'string',
            group: 'routes',
            initialValue: '/login',
            validation: Rule => Rule.required(),
        }),
        defineField({
            name: 'disableDraftRoute',
            title: 'Disable Draft Mode Route',
            type: 'string',
            group: 'routes',
            initialValue: '/api/disable-draft',
            validation: Rule => Rule.required(),
        }),
    ],
    preview: {
        prepare() {
            return {
                title: 'UI Strings',
                subtitle: 'System messages and labels',
            }
        },
    },
})

